# Generated by Django 6.0.3 on 2026-04-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
